module.exports = {
  extends: "./tslint-base.json",
  rulesDirectory: ["codelyzer"],
  rules: {
    "no-unnecessary-class": [
      true,
      "allow-constructor-only",
      "allow-static-only",
      "allow-empty-class",
    ],
    "member-access": [true],
    "member-ordering": [
      true,
      "public-before-private",
      "static-before-instance",
      "variables-before-functions",
    ],
    "adjacent-overload-signatures": [
      true,
      {
        "ignore-accessors": true,
      },
    ],
    "unified-signatures": true,
    "prefer-function-over-method": [false],
    "no-unbound-method": [true, "ignore-static"],
    "no-invalid-this": [true, "check-function-in-method"],
    "static-this": true,
    "no-this-assignment": true,
    "unnecessary-constructor": true,
    "no-duplicate-super": true,
    "new-parens": true,
    "no-misused-new": true,
    "no-construct": true,
    "no-empty-interface": true,
    "prefer-method-signature": true,
    "interface-over-type-literal": true,
    "function-constructor": true,
    "no-parameter-reassignment": true,
    "no-void-expression": true,
    "return-undefined": true,
    "no-arg": true,
    "only-arrow-functions": true,
    "ordered-imports": false,
    "arrow-parens": [true],
    "arrow-return-shorthand": [true, "multiline"],
    "no-unnecessary-callback-wrapper": true,
    "unnecessary-bind": true,
    "await-promise": true,
    "no-async-without-await": true,
    "no-return-await": true,
    "prefer-const": true,
    "no-var-keyword": true,
    "no-shadowed-variable": [
      true,
      {
        temporalDeadZone: false,
      },
    ],
    "one-variable-per-declaration": [true, "ignore-for-loop"],
    "no-duplicate-variable": [true, "check-parameters"],
    "no-unnecessary-initializer": true,
    "no-import-side-effect": [
      true,
      {
        "ignore-module": "(hammerjs|core-js|zone.js)",
      },
    ],
    "no-duplicate-imports": true,
    "import-blacklist": [true, "rxjs/Rx"],
    "no-require-imports": true,
    "no-reference": true,
    typedef: [true, "call-signature", "property-declaration"],
    "no-inferrable-types": true,
    "use-default-type-parameter": true,
    "no-object-literal-type-assertion": true,
    "no-angle-bracket-type-assertion": true,
    "no-unnecessary-type-assertion": true,
    "callable-types": true,
    "no-non-null-assertion": true,
    "array-type": false,
    "prefer-object-spread": true,
    "object-literal-shorthand": true,
    "object-literal-key-quotes": [true, "as-needed"],
    "no-string-literal": true,
    quotemark: [true, "single", "avoid-template", "avoid-escape"],
    "no-invalid-template-strings": true,
    "triple-equals": [true, "allow-null-check"],
    "strict-comparisons": [
      true,
      {
        "allow-object-equal-comparison": true,
        "allow-string-order-comparison": true,
      },
    ],
    "increment-decrement": [true, "allow-post"],
    "restrict-plus-operands": true,
    "binary-expression-operand-order": true,
    "no-dynamic-delete": true,
    "no-bitwise": true,
    "use-isnan": true,
    "no-conditional-assignment": true,
    "no-tautology-expression": true,
    "no-boolean-literal-compare": true,
    "strict-boolean-expressions": [
      true,
      "allow-undefined-union",
      "allow-string",
      "allow-enum",
      "allow-number",
      "allow-mix",
      "allow-rhs",
    ],
    "prefer-while": true,
    "prefer-for-of": true,
    forin: true,
    "no-for-in-array": true,
    "switch-default": true,
    "no-switch-case-fall-through": true,
    "no-duplicate-switch-case": true,
    "no-unsafe-finally": true,
    encoding: true,
    "cyclomatic-complexity": [true, 20],
    "max-file-line-count": [true, 1000],
    "max-line-length": [
      true,
      {
        limit: 180,
        "ignore-pattern":
          "^import |^export {(.*?)}|class [a-zA-Z]+ implements |// ",
      },
    ],
    indent: [true, "spaces", 2],
    eofline: true,
    curly: true,
    whitespace: [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-module",
      "check-separator",
      "check-rest-spread",
      "check-type",
      "check-typecast",
      "check-type-operator",
      "check-preblock",
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        parameter: "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace",
      },
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        parameter: "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace",
      },
    ],
    "space-before-function-paren": [
      true,
      {
        anonymous: "never",
        named: "never",
        asyncArrow: "always",
        method: "never",
        constructor: "never",
      },
    ],
    "space-within-parens": true,
    "import-spacing": true,
    "no-trailing-whitespace": true,
    "newline-before-return": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-whitespace",
      "check-else",
      "check-catch",
      "check-finally",
    ],
    "no-consecutive-blank-lines": [true, 1],
    semicolon: [true, "always", "strict-bound-class-methods"],
    align: [true, "elements", "members", "parameters", "statements"],
    "trailing-comma": [
      true,
      {
        esSpecCompliant: true,
      },
    ],
    "class-name": true,
    "interface-name": [true, "always-prefix"],
    "variable-name": [
      true,
      "check-format",
      "allow-leading-underscore",
      "require-const-for-all-caps",
      "ban-keywords",
    ],
    "comment-format": [true, "check-space"],
    "jsdoc-format": [true, "check-multiline-start"],
    "no-redundant-jsdoc": true,
    "ban-ts-ignore": true,
    "no-console": [true, "log", "debug", "info", "time", "timeEnd", "trace"],
    "no-debugger": true,
    "no-eval": true,
    "no-string-throw": true,
    "no-namespace": true,
    "no-internal-module": true,
    "number-literal-format": true,
    radix: true,
    "no-unused-expression": [true, "allow-fast-null-checks"],
    "no-empty": false,
    "no-sparse-arrays": true,
    "ban-comma-operator": true,
    "template-banana-in-box": true,
    "contextual-lifecycle": true,
    "contextual-decorator": true,
    "no-pipe-impure": true,
    "template-no-negated-async": true,
    "template-i18n": [false],
    "component-max-inline-declarations": true,
    "no-attribute-decorator": true,
    "no-conflicting-lifecycle": true,
    "no-forward-ref": true,
    "no-input-rename": true,
    "no-lifecycle-call": true,
    "no-output-native": true,
    "no-output-on-prefix": true,
    "no-output-rename": true,
    "template-no-call-expression": false,
    "no-unused-css": false,
    "prefer-output-readonly": true,
    "template-conditional-complexity": [true, 4],
    "template-cyclomatic-complexity": false,
    "use-lifecycle-interface": true,
    "use-pipe-decorator": true,
    "use-pipe-transform-interface": true,
    "use-component-view-encapsulation": true,
    "component-class-suffix": true,
    "component-selector": [false],
    "directive-class-suffix": true,
    "directive-selector": [true, "attribute", ["ngx", "test"], "camelCase"],
    "import-destructuring-spacing": true,
    "no-queries-metadata-property": true,
    "prefer-inline-decorator": true,
    "no-host-metadata-property": true,
    "no-inputs-metadata-property": true,
    "no-outputs-metadata-property": true,
    deprecation: {
      severity: "warn",
    },
    "max-classes-per-file": false,
    "no-var-requires": false,
    "object-literal-sort-keys": false,
  },
};
